beneficiaries/urls.py
from django.urls import path

from . import views

app_name = "beneficiaries"

urlpatterns = [
    path("", views.index, name="index"),

    path("<int:beneficiary_id>/", views.show, name="show"),

    path("<int:beneficiary_id>/edition", views.edit, name="edit"),
    path("<int:beneficiary_id>/change", views.change, name="change"),
    path(
        "<int:beneficiary_id>/edition-telephone",
        views.edit_phone,
        name="edit_phone"
    ),
    path(
        "<int:beneficiary_id>/change-phone",
        views.change_phone,
        name="change_phone"
    ),

    path("nouveau", views.new, name="new"),
    path("create", views.create, name="create"),

    path(
        "<int:beneficiary_id>/prise-en-charge",
        views.assign_form,
        name="assign_form"
    ),

    path(
        "<int:beneficiary_id>/assign",
        views.assign_action,
        name="assign_action"
    ),

    path(
        "<int:beneficiary_id>/fin-accompagnement",
        views.end_of_support_form,
        name="end_of_support_form"
    ),
    path(
        "<int:beneficiary_id>/end-of-support",
        views.end_of_support_action,
        name="end_of_support_action"
    ),
]

plateforme_numerique_pour_tous/urls.py
from django.conf import settings

"""
URL configuration for plateforme_numerique_pour_tous project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.urls import include, path

from beneficiaries import views as beneficiaries_views
from directory import views as directory_views
from educational import views as educational_views

urlpatterns = [
    path("", lambda _: redirect("/beneficiaires")),
    path("beneficiaires/", include("beneficiaries.urls")),
    path("admin/", admin.site.urls),
    path("compte/", include("django.contrib.auth.urls")),
    path("compte/connexion/", auth_views.LoginView.as_view(), name="login"),
    path(
        "compte/mot-de-passe-oublie/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "compte/mot-de-passe-oublie/envoye",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "subventions",
        beneficiaries_views.subsidies_index,
        name="subsidies_index"
    ),
    path(
        "repertoire", 
        directory_views.structures_index, 
        name="structures_index"
    ),
    path(
        "contenus-pedagogiques", 
        educational_views.educational_index, 
        name="educational_index"
    ),
]

if settings.DEBUG:
    urlpatterns += path(
        "__debug__/",
        include("debug_toolbar.urls")
    ),

beneficiaries/models.py
import uuid

from django import forms
from django.core import validators
from django.db import models
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.forms import ModelForm

from phonenumber_field.modelfields import PhoneNumberField

from structures.models import Structure


class Beneficiary(models.Model):
    MAN = "M"
    WOMAN = "W"
    GENDERS = {WOMAN: "Madame", MAN: "Monsieur"}
    AGE_GROUP = {
        "": "Choisissez votre classe d’âge ici",
        "16-19": "16-19",
        "20-24": "20-24",
        "25-29": "25-29",
        "30-34": "30-34",
        "35-39": "35-39",
        "40-44": "40-44",
        "45-49": "45-49",
        "50-54": "50-54",
        "55-59": "55-59",
        "60-64": "60-64",
        "65-69": "65-69",
        "70-74": "70-74",
        "75-": "75 ou +",
    }
    CREATED = "created"
    ACTIVE = "active"
    DONE = "done"
    EXPIRED = "expired"
    STATUSES = {
        CREATED: "Actif",
        ACTIVE: "Pris en charge",
        DONE: "Terminé",
        EXPIRED: "Expiré",
    }

    gender = models.CharField(
        "Madame / Monsieur",
        max_length=1,
        choices=GENDERS,
        null=False,
        blank=False,
        default=None,  # To avoid another radio for unselected
    )
    last_name = models.CharField("Nom", max_length=200, null=False, blank=False)
    first_name = models.CharField("Prénom", max_length=200, null=False, blank=False)
    age = models.CharField(
        "Classe d’âge", max_length=5, choices=AGE_GROUP, null=False, blank=False
    )
    phone_number = PhoneNumberField(
        "Numéro de téléphone",
        region="FR",
        null=False,
        blank=False,
        help_text="Formats acceptés : \
            01.02.03.04.05, 0102030405, +33102030405, 01 02 03 04 05",
    )
    status = models.CharField("Statut", choices=STATUSES, default=CREATED)
    structure_counselor = models.ForeignKey(
        Structure,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name="structure_counselor",
        verbose_name="Structure d’orientation",
    )
    structure_operator = models.ForeignKey(
        Structure,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name="structure_operator",
        verbose_name="Structure de prise en charge",
    )
    # unique is setted in migration due to some technical constraint
    uuid = models.UUIDField(
        "Code d’identification unique",
        primary_key=False,
        default=uuid.uuid4,
        help_text="Formats acceptés : 1234567 ou 1234-567",
    )
    comment = models.TextField(
        "Commentaire",
        blank=True,
        null=True,
        help_text="Ajoutez un commentaire à propos du bénéficiaire",
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_gender(self):
        return self.GENDERS[self.gender]

    def get_status(self):
        return self.STATUSES[self.status]

    def get_huuid(self):
        return "{}-{}".format(str(self.uuid)[:4], str(self.uuid)[4:7])

    def get_entity_verbose_name(self):
        return self._meta.verbose_name

    def get_anonymized_phone_number(self):
        return "XX XX XX {}".format(self.phone_number.as_national[8:])

    class Meta:
        permissions = (
            ("assign_beneficiary", "assign beneficiary"),
            ("end_of_support_beneficiary", "end of support beneficiary"),
            ("change_beneficiary_phone", "change beneficiary phone"),
            ("view_subsidies", "view subsidies"),
        )
        verbose_name = "bénéficiaire"


class BeneficiaryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        PLACEHOLDER_FORMAT = "Inscrivez votre {field} ici"

        self.fields["first_name"].widget.attrs.update(
            {"placeholder": PLACEHOLDER_FORMAT.format(field="prénom")}
        )
        self.fields["last_name"].widget.attrs.update(
            {"placeholder": PLACEHOLDER_FORMAT.format(field="nom")}
        )
        self.fields["phone_number"].widget.attrs.update(
            {"placeholder": PLACEHOLDER_FORMAT.format(field="numéro de téléphone")}
        )
        self.fields["gender"].widget.attrs.update({"class": "form-check-input"})
        self.fields["structure_counselor"].widget.attrs.update({"readonly": "readonly"})
        self.fields["structure_counselor"].label = "Structure"

    def clean(self):
        try:
            current_beneficiary_id = self.instance.id

            cleaned_data = super().clean()
            first_name = cleaned_data.get("first_name")
            last_name = cleaned_data.get("last_name")
            phone_number = cleaned_data.get("phone_number")

            similar_beneficiary = Beneficiary.objects.get(
                first_name__unaccent__icontains=first_name,
                last_name__unaccent__icontains=last_name,
                phone_number=phone_number,
            )

        except ValueError:
            raise ValidationError("Le formulaire est vide")

        # No similar beneficiary, so pass
        except ObjectDoesNotExist:
            return

        # Similar beneficiary is the current user, so pass
        if similar_beneficiary.id == current_beneficiary_id:
            return

        raise ValidationError(
            mark_safe(
                '<a href="{url}">Utilisateur</a> déjà existant'
                " avec le même nom et numéro de téléphone".format(
                    url=reverse("beneficiaries:show", args=[similar_beneficiary.id])
                )
            )
        )

    class Meta:
        model = Beneficiary
        fields = "__all__"
        exclude = ["status", "structure_operator", "uuid"]
        widgets = {
            "gender": forms.RadioSelect(),
            "status": forms.HiddenInput(),
            "structure_counselor": forms.HiddenInput(),
        }
        error_messages = {
            "phone_number": {"unique": "Ce numéro de téléphone est déjà utilisé"}
        }


class BeneficiaryFormPhone(ModelForm):
    class Meta:
        model = Beneficiary
        fields = ["phone_number"]


class BeneficiaryFormSearch(ModelForm):
    search_by_uuid = forms.CharField(
        validators=[validators.MinLengthValidator(7), validators.MaxLengthValidator(8)],
        help_text="Formats acceptés : xxxxxxx ou xxxx-xxx",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["phone_number"].widget.attrs.update(
            {
                "placeholder": "Rechercher par numéro de téléphone",
                "type": "tel",
                "minlength": 10,
                "size": 35,
            }
        )
        self.fields["phone_number"].required = False

        self.fields["search_by_uuid"].widget.attrs.update(
            {
                "placeholder": "Rechercher par code d’identification",
                "minlength": 7,
                "maxlength": 8,
            }
        )
        self.fields["search_by_uuid"].required = False

    def clean(self):
        cleaned_data = super().clean()
        uuid = cleaned_data.get("search_by_uuid")
        phone_number = cleaned_data.get("phone_number")

        if not uuid and not phone_number:
            raise ValidationError(
                mark_safe(
                    "Pour effectuer la recherche de bénéficiaire,<br/>"
                    "<strong>au moins 1 des 2 champs"
                    "doit être renseigné</strong>."
                )
            )

    class Meta:
        model = Beneficiary
        fields = ["search_by_uuid", "phone_number"]


class BeneficiaryFormAssign(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # We want to display the structure name
        # We need to submit structure id, but :
        # #select doesn't have readonly attribut so user can change, and
        # disabled attribut dont submit the field
        # -> So the structure name is displayed
        #    by the template through user informations

    class Meta:
        model = Beneficiary
        fields = ["status", "structure_operator"]
        widgets = {
            "status": forms.HiddenInput(),
            "structure_operator": forms.HiddenInput(),
        }


class BeneficiaryFormEndOfSupport(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update({"readonly": "readonly"})
        self.fields["last_name"].widget.attrs.update({"readonly": "readonly"})

    class Meta:
        model = Beneficiary
        fields = ["status", "structure_operator", "first_name", "last_name"]
        widgets = {
            "status": forms.HiddenInput(),
            "structure_operator": forms.HiddenInput(),
        }


class Subsidy:
    subsidies_by_year = {
        "2024": {
            "year": 2024,
            "total": 0,
            "new": 0,
            "startSupportCount": 0,
            "endSupportCount": 0,
            "t1": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
            "t2": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
            "t3": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
            "t4": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
        },
        "2025": {
            "year": 2025,
            "total": 0,
            "new": 0,
            "startSupportCount": 0,
            "endSupportCount": 0,

core/templates/footer.html
{% load static %}

<div class="row my-5">
  <div class="col-6 align-self-center">
    <p class="text-end">
      Un programme porté par la <strong>Métropole du Grand Paris</strong><br/>et le <strong>Hub&nbsp;Francil'in</strong>
    </p>
  </div>

  <div class="col-6">
    <img src="{% static '/MGP.jpg' %}" height="125" class="me-1"/>
    <img src="{% static '/francilin.png' %}" height="60" />
  </div>
</div>
<div class="row text-center mb-5">
  <div class="col-6">
    <a href="{% static '/Mentions légales.pdf' %}">
      <small>Mentions légales</small>
    </a>
  </div>
  <div class="col-6">
    <a href="{% static '/Conditions générales d\'utilisations.pdf' %}">
      <small>Conditions générales d'utilisations</small>
    </a>
  </div>
</div>

core/templates/link-support.html
<a class="nav-link" href="mailto:contact-npt@francilin.fr">
  Contacter un administrateur
</a>

core/templates/master.html
{% load static %}
{% load bootstrap_icons %}

<html>
  <head>
    <title>Plateforme numérique pour tous</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="shortcut icon" type="image/png" href="{% static '/favicon.ico' %}" >

    {% load django_bootstrap5 %}

    {% bootstrap_css %}
    {% bootstrap_javascript %}

    <style>
      .bi {
        width: 24;
        height: 24;
      }

      .btn-outline-primary {
        --bs-btn-color: #007b9c;
        --bs-btn-border-color: #007b9c;

        --bs-btn-hover-bg: #007b9c;
        --bs-btn-hover-border-color: #007b9c;

        --bs-btn-active-border-color: #007b9c;
        --bs-btn-active-bg: #007b9c;

        --bs-btn-disabled-color: #007b9c;
        --bs-btn-disabled-border-color: #007b9c;
      }

      .link-primary {
        color: #007b9c!important;
      }

      .not-allowed {
        cursor: not-allowed;
      }

      input:read-only {
        background-color: #e9ecef;
        cursor: default;
      }

      .accordion {
        --bs-accordion-active-bg: transparent;
      }
      .accordion.accordion-flush {
        --bs-accordion-border-width: 0;
      }
      .accordion-button:focus {
        box-shadow: none;
        border-color: transparent;
      }
    </style>
  </head>
  <body>
    {% if messages %}
      {% for message in messages %}
        <div{% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">
          {{ message|safe }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="container">
      <nav class="navbar navbar-expand-xl">
        <div class="container-fluid px-0">
          <a class="navbar-brand" href="{% url 'beneficiaries:index' %}" title="Retour à l’accueil">
            <img src="{% static '/logo_npt.png' %}" width="200" />
          </a>

          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarPrimary"
            aria-controls="navbarPrimary"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          {% if user.is_authenticated %}
            <form action="{% url 'logout' %}" method="post" class="mb-0">
              {% csrf_token %}
              {{ user }}
              {% if user.structure %}
                | {{ user.structure}} |
              {% endif %}

              {% for group in user.groups.all %}
                <span class="badge text-bg-secondary text-lowercase">{{ group.name }}</span>
              {% endfor %}

              <button type="submit" href="{% url 'logout' %}" class="btn fs-2 pe-0">
                {% bs_icon 'box-arrow-right' %}
              </button>
            </form>
          {% endif %}
        </div>
      </nav>
      <nav class="navbar navbar-expand-md mb-3 border-bottom pb-3 pt-3">
        <div class="container-fluid px-0">
          <button
            class="navbar-toggler"
            type="button"
            data-bs-toggle="collapse"
            data-bs-target="#navbarSecondary"
            aria-controls="navbarSecondary"
            aria-expanded="false"
            aria-label="Toggle navigation"
          >
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse" id="navbarSecondary">
            <ul class="nav nav-pills">
              {% with request.resolver_match.url_name as url_name %}
                {% if perms.beneficiaries.view_beneficiary %}
                  <li class="nav-item">
                    <a href="{% url 'beneficiaries:index' %}" class="nav-link {% if url_name == 'index' %}active{% endif %}">Bénéficiaires</a>
                  </li>
                {% endif %}

                {% if perms.beneficiaries.view_subsidies %}
                  <li class="nav-item">
                    <a href="{% url 'subsidies_index' %}" class="nav-link {% if url_name == 'subsidies_index' %}active{% endif %}">Subventions</a>
                  </li>
                {% endif %}

                <li class="nav-item">
                  {% include "link-support.html" %}
                </li>
              {% endwith %}

              <li class="nav-item">
                <a href="{% url 'structures_index' %}" 
                  class="nav-link {% if url_name == 'structures_index' %}active{% endif %}">
                  Répertoire structures
                </a>
              </li>

              <li class="nav-item">
                <a href="{% url 'educational_index' %}" 
                  class="nav-link {% if url_name == 'educational_index' %}active{% endif %}">
                  Contenus pédagogiques
                </a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
      {% block content %}
      {% endblock %}

      {% include "footer.html" %}
    </div>
  </body>
</html>