beneficiaries/urls.py
from django.urls import path

from . import views

app_name = "beneficiaries"

urlpatterns = [
    path("", views.index, name="index"),

    path("<int:beneficiary_id>/", views.show, name="show"),

    path("<int:beneficiary_id>/edition", views.edit, name="edit"),
    path("<int:beneficiary_id>/change", views.change, name="change"),
    path(
        "<int:beneficiary_id>/edition-telephone",
        views.edit_phone,
        name="edit_phone"
    ),
    path(
        "<int:beneficiary_id>/change-phone",
        views.change_phone,
        name="change_phone"
    ),

    path("nouveau", views.new, name="new"),
    path("create", views.create, name="create"),

    path(
        "<int:beneficiary_id>/prise-en-charge",
        views.assign_form,
        name="assign_form"
    ),

    path(
        "<int:beneficiary_id>/assign",
        views.assign_action,
        name="assign_action"
    ),

    path(
        "<int:beneficiary_id>/fin-accompagnement",
        views.end_of_support_form,
        name="end_of_support_form"
    ),
    path(
        "<int:beneficiary_id>/end-of-support",
        views.end_of_support_action,
        name="end_of_support_action"
    ),
]

plateforme_numerique_pour_tous/urls.py
from django.conf import settings

"""
URL configuration for plateforme_numerique_pour_tous project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.shortcuts import redirect
from django.urls import include, path

from beneficiaries import views as beneficiaries_views
from directory import views as directory_views
from educational import views as educational_views

urlpatterns = [
    path("", lambda _: redirect("/beneficiaires")),
    path("beneficiaires/", include("beneficiaries.urls")),
    path("admin/", admin.site.urls),
    path("compte/", include("django.contrib.auth.urls")),
    path("compte/connexion/", auth_views.LoginView.as_view(), name="login"),
    path(
        "compte/mot-de-passe-oublie/",
        auth_views.PasswordResetView.as_view(),
        name="password_reset",
    ),
    path(
        "compte/mot-de-passe-oublie/envoye",
        auth_views.PasswordResetDoneView.as_view(),
        name="password_reset_done",
    ),
    path(
        "subventions",
        beneficiaries_views.subsidies_index,
        name="subsidies_index"
    ),
    path(
        "repertoire", 
        directory_views.structures_index, 
        name="structures_index"
    ),
    path(
        "contenus-pedagogiques", 
        educational_views.educational_index, 
        name="educational_index"
    ),
]

if settings.DEBUG:
    urlpatterns += path(
        "__debug__/",
        include("debug_toolbar.urls")
    ),

beneficiaries/models.py
import uuid

from django import forms
from django.core import validators
from django.db import models
from django.core.exceptions import ObjectDoesNotExist, ValidationError
from django.utils.safestring import mark_safe
from django.urls import reverse
from django.forms import ModelForm

from phonenumber_field.modelfields import PhoneNumberField

from structures.models import Structure


class Beneficiary(models.Model):
    MAN = "M"
    WOMAN = "W"
    GENDERS = {WOMAN: "Madame", MAN: "Monsieur"}
    AGE_GROUP = {
        "": "Choisissez votre classe d’âge ici",
        "16-19": "16-19",
        "20-24": "20-24",
        "25-29": "25-29",
        "30-34": "30-34",
        "35-39": "35-39",
        "40-44": "40-44",
        "45-49": "45-49",
        "50-54": "50-54",
        "55-59": "55-59",
        "60-64": "60-64",
        "65-69": "65-69",
        "70-74": "70-74",
        "75-": "75 ou +",
    }
    CREATED = "created"
    ACTIVE = "active"
    DONE = "done"
    EXPIRED = "expired"
    STATUSES = {
        CREATED: "Actif",
        ACTIVE: "Pris en charge",
        DONE: "Terminé",
        EXPIRED: "Expiré",
    }

    gender = models.CharField(
        "Madame / Monsieur",
        max_length=1,
        choices=GENDERS,
        null=False,
        blank=False,
        default=None,  # To avoid another radio for unselected
    )
    last_name = models.CharField("Nom", max_length=200, null=False, blank=False)
    first_name = models.CharField("Prénom", max_length=200, null=False, blank=False)
    age = models.CharField(
        "Classe d’âge", max_length=5, choices=AGE_GROUP, null=False, blank=False
    )
    phone_number = PhoneNumberField(
        "Numéro de téléphone",
        region="FR",
        null=False,
        blank=False,
        help_text="Formats acceptés : \
            01.02.03.04.05, 0102030405, +33102030405, 01 02 03 04 05",
    )
    status = models.CharField("Statut", choices=STATUSES, default=CREATED)
    structure_counselor = models.ForeignKey(
        Structure,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name="structure_counselor",
        verbose_name="Structure d’orientation",
    )
    structure_operator = models.ForeignKey(
        Structure,
        models.SET_NULL,
        blank=True,
        null=True,
        related_name="structure_operator",
        verbose_name="Structure de prise en charge",
    )
    # unique is setted in migration due to some technical constraint
    uuid = models.UUIDField(
        "Code d’identification unique",
        primary_key=False,
        default=uuid.uuid4,
        help_text="Formats acceptés : 1234567 ou 1234-567",
    )
    comment = models.TextField(
        "Commentaire",
        blank=True,
        null=True,
        help_text="Ajoutez un commentaire à propos du bénéficiaire",
    )

    def __str__(self):
        return f"{self.first_name} {self.last_name}"

    def get_gender(self):
        return self.GENDERS[self.gender]

    def get_status(self):
        return self.STATUSES[self.status]

    def get_huuid(self):
        return "{}-{}".format(str(self.uuid)[:4], str(self.uuid)[4:7])

    def get_entity_verbose_name(self):
        return self._meta.verbose_name

    def get_anonymized_phone_number(self):
        return "XX XX XX {}".format(self.phone_number.as_national[8:])

    class Meta:
        permissions = (
            ("assign_beneficiary", "assign beneficiary"),
            ("end_of_support_beneficiary", "end of support beneficiary"),
            ("change_beneficiary_phone", "change beneficiary phone"),
            ("view_subsidies", "view subsidies"),
        )
        verbose_name = "bénéficiaire"


class BeneficiaryForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        PLACEHOLDER_FORMAT = "Inscrivez votre {field} ici"

        self.fields["first_name"].widget.attrs.update(
            {"placeholder": PLACEHOLDER_FORMAT.format(field="prénom")}
        )
        self.fields["last_name"].widget.attrs.update(
            {"placeholder": PLACEHOLDER_FORMAT.format(field="nom")}
        )
        self.fields["phone_number"].widget.attrs.update(
            {"placeholder": PLACEHOLDER_FORMAT.format(field="numéro de téléphone")}
        )
        self.fields["gender"].widget.attrs.update({"class": "form-check-input"})
        self.fields["structure_counselor"].widget.attrs.update({"readonly": "readonly"})
        self.fields["structure_counselor"].label = "Structure"

    def clean(self):
        try:
            current_beneficiary_id = self.instance.id

            cleaned_data = super().clean()
            first_name = cleaned_data.get("first_name")
            last_name = cleaned_data.get("last_name")
            phone_number = cleaned_data.get("phone_number")

            similar_beneficiary = Beneficiary.objects.get(
                first_name__unaccent__icontains=first_name,
                last_name__unaccent__icontains=last_name,
                phone_number=phone_number,
            )

        except ValueError:
            raise ValidationError("Le formulaire est vide")

        # No similar beneficiary, so pass
        except ObjectDoesNotExist:
            return

        # Similar beneficiary is the current user, so pass
        if similar_beneficiary.id == current_beneficiary_id:
            return

        raise ValidationError(
            mark_safe(
                '<a href="{url}">Utilisateur</a> déjà existant'
                " avec le même nom et numéro de téléphone".format(
                    url=reverse("beneficiaries:show", args=[similar_beneficiary.id])
                )
            )
        )

    class Meta:
        model = Beneficiary
        fields = "__all__"
        exclude = ["status", "structure_operator", "uuid"]
        widgets = {
            "gender": forms.RadioSelect(),
            "status": forms.HiddenInput(),
            "structure_counselor": forms.HiddenInput(),
        }
        error_messages = {
            "phone_number": {"unique": "Ce numéro de téléphone est déjà utilisé"}
        }


class BeneficiaryFormPhone(ModelForm):
    class Meta:
        model = Beneficiary
        fields = ["phone_number"]


class BeneficiaryFormSearch(ModelForm):
    search_by_uuid = forms.CharField(
        validators=[validators.MinLengthValidator(7), validators.MaxLengthValidator(8)],
        help_text="Formats acceptés : xxxxxxx ou xxxx-xxx",
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields["phone_number"].widget.attrs.update(
            {
                "placeholder": "Rechercher par numéro de téléphone",
                "type": "tel",
                "minlength": 10,
                "size": 35,
            }
        )
        self.fields["phone_number"].required = False

        self.fields["search_by_uuid"].widget.attrs.update(
            {
                "placeholder": "Rechercher par code d’identification",
                "minlength": 7,
                "maxlength": 8,
            }
        )
        self.fields["search_by_uuid"].required = False

    def clean(self):
        cleaned_data = super().clean()
        uuid = cleaned_data.get("search_by_uuid")
        phone_number = cleaned_data.get("phone_number")

        if not uuid and not phone_number:
            raise ValidationError(
                mark_safe(
                    "Pour effectuer la recherche de bénéficiaire,<br/>"
                    "<strong>au moins 1 des 2 champs"
                    "doit être renseigné</strong>."
                )
            )

    class Meta:
        model = Beneficiary
        fields = ["search_by_uuid", "phone_number"]


class BeneficiaryFormAssign(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # We want to display the structure name
        # We need to submit structure id, but :
        # #select doesn't have readonly attribut so user can change, and
        # disabled attribut dont submit the field
        # -> So the structure name is displayed
        #    by the template through user informations

    class Meta:
        model = Beneficiary
        fields = ["status", "structure_operator"]
        widgets = {
            "status": forms.HiddenInput(),
            "structure_operator": forms.HiddenInput(),
        }


class BeneficiaryFormEndOfSupport(ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["first_name"].widget.attrs.update({"readonly": "readonly"})
        self.fields["last_name"].widget.attrs.update({"readonly": "readonly"})

    class Meta:
        model = Beneficiary
        fields = ["status", "structure_operator", "first_name", "last_name"]
        widgets = {
            "status": forms.HiddenInput(),
            "structure_operator": forms.HiddenInput(),
        }


class Subsidy:
    subsidies_by_year = {
        "2024": {
            "year": 2024,
            "total": 0,
            "new": 0,
            "startSupportCount": 0,
            "endSupportCount": 0,
            "t1": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
            "t2": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
            "t3": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
            "t4": {
                "subsidies": 0,
                "startSupportCount": 0,
                "endSupportCount": 0,
                "new": 0,
            },
        },
        "2025": {
            "year": 2025,
            "total": 0,
            "new": 0,
            "startSupportCount": 0,
            "endSupportCount": 0,

beneficiaries/templates/beneficiaries/assign_form.html
{% extends 'master.html' %}

{% load widget_tweaks %}

{% block content %}
  <h2>Profil {{beneficiary.get_entity_verbose_name}} de : {{ beneficiary }}</h2>

  <form action="{% url 'beneficiaries:assign_action' beneficiary.id %}" method="post">
    {% csrf_token %}
    <div class="row">
      <div class="col-4">
        <label>Structure de médiation qui assure la prise en charge :</label>
        <input disabled value="{{ user.structure|default_if_none:'' }}" class="form-control"/>
      </div>
    </div>
    {% if form.non_field_errors %}
      <div class="alert alert-danger fw-bold">
        {{ form.non_field_errors.as_text }}
      </div>
    {% endif %}

    {% for field in form %}
      <div class="mb-4 form-required">
        {{ field }}
      </div>
    {% endfor %}

    {% for field in start_support_form %}
        {% if field.widget_type != "hidden" %}
          <div class="row">
            <div class="mb-4 form-required col-4">
              {{ field.label_tag }}

              {% if field.errors %}
                {{ field|add_class:"form-control is-invalid" }}
              {% else %}
                {{ field|add_class:"form-control" }}
              {% endif %}

              {% if field.help_text %}
                <small class="form-text text-muted">{{ field.help_text }}</small>
              {% endif %}

              {% if field.errors %}
                <div class="invalid-feedback fw-bold">
                  {{ field.errors.as_text }}
                </div>
              {% endif %}
            </div>
          </div>
        {% else %}
          {{ field }}
        {% endif %}
    {% endfor %}

    <div class="mb-3">
      <input type="checkbox" required class="me-1" id="cgu"/>
      <label class="d-inline" for="cgu">Le bénéficiaire a effectué un test de placement et a été informé qu'une fois pris en charge par ma structure, il ne pourra pas bénéficier d'un accompagnement par une autre structure de médiation dans le cadre de Numérique pour tous.</label>
    </div>
    <button class="btn btn-primary d-block mb-3" type="submit">Prendre en charge</button>
  </form>
{% endblock %}

beneficiaries/templates/beneficiaries/edit_phone.html
{% extends "master.html" %}

{% load widget_tweaks %}

{% block content %}
  <form action="{% url 'beneficiaries:change_phone' beneficiary.id %}" method="post">
    {% csrf_token %}
    <fieldset>
      <h2>Édition du profil de : {{ beneficiary }}</h2>

      {% if form.non_field_errors %}
        <div class="alert alert-danger fw-bold">
          {{ form.non_field_errors.as_text }}
        </div>
      {% endif %}

      <div class="mb-4">
        <label>Structure de l’orienteur :</label>
        <input disabled value="{{ user.structure|default_if_none:'' }}" class="form-control"/>
      </div>

      <hr/>

      {% for field in form %}
        <div class="mb-4 form-required">
          {% if field.widget_type != "hidden" %}
            {{ field.label_tag }}
          {% endif %}

          {% if field.errors %}
            {{ field|add_class:"form-control is-invalid" }}
          {% else %}
            {{ field|add_class:"form-control" }}
          {% endif %}

          {% if field.help_text %}
            <small class="form-text text-muted">{{ field.help_text }}</small>
          {% endif %}

          {% if field.errors %}
            <div class="invalid-feedback fw-bold">
              {{ field.errors.as_text }}
            </div>
          {% endif %}
        </div>
      {% endfor %}

      <a href="{% url 'beneficiaries:index' %}" class="mx-3 link-secondary">Annuler</a>
      <button type="submit" class="btn btn-outline-primary">Éditer</button>
    </fieldset>
  </form>
{% endblock %}

beneficiaries/templates/beneficiaries/end_of_support_form.html
{% extends 'master.html' %}

{% load bootstrap_icons %}
{% load widget_tweaks %}

{% block content %}

  <h2>Profil {{beneficiary.get_entity_verbose_name}} de : {{ beneficiary }}</h2>
  <div class="alert alert-secondary" role="alert">{% bs_icon "exclamation-diamond" %}&nbsp;L'ensemble des éléments est obligatoire</div>

  <form action="{% url 'beneficiaries:end_of_support_action' beneficiary.id %}" method="post">
    {% csrf_token %}

    {% if form.non_field_errors %}
      <div class="alert alert-danger fw-bold">
        {{ form.non_field_errors.as_text }}
      </div>
    {% endif %}


    <div class="row">
      <div class="mb-4 col">
        <label>Structure de l’opérateur :</label>
        <input disabled value="{{ user.structure|default_if_none:'' }}" class="form-control"/>
      </div>

    {% for field in form %}
        {% if field.widget_type != "hidden" %}
          <div class="mb-4 form-required col">
            {{ field.label_tag }}

            {% if field.errors %}
              {{ field|add_class:"form-control is-invalid" }}
            {% else %}
              {{ field|add_class:"form-control" }}
            {% endif %}

            {% if field.help_text %}
              <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}
            {% if field.errors %}
              <div class="invalid-feedback fw-bold">
                {{ field.errors.as_text }}
              </div>
            {% endif %}
          </div>
          {% else %}
            {{ field }}
        {% endif %}
    {% endfor %}
    </div>

    <hr/>

    {% for field in end_of_support_form %}
      <div class="row">
        {% if field.widget_type != "hidden" %}
          <div class="mb-4 form-required col-4">
            {{ field.label_tag }}

            {% if field.errors %}
              {{ field|add_class:"form-control is-invalid" }}
            {% else %}
              {{ field|add_class:"form-control" }}
            {% endif %}

            {% if field.help_text %}
              <small class="form-text text-muted">{{ field.help_text }}</small>
            {% endif %}

            {% if field.errors %}
              <div class="invalid-feedback fw-bold">
                {{ field.errors.as_text }}
              </div>
            {% endif %}
          </div>
        {% else %}
          {{ field }}
        {% endif %}
      </div>
    {% endfor %}

    <div>
      <a href="{% url 'beneficiaries:index' %}" class="mx-3 link-secondary">Annuler</a>
      <button type="submit" class="btn btn-primary">Mettre fin à la prise en charge</button>
    </div>
  </form>

{% endblock %}

beneficiaries/templates/beneficiaries/index.html
{% extends "master.html" %}

{% load static %}
{% load widget_tweaks %}
{% load bootstrap_icons %}

{% block content %}
  <nav class="navbar navbar-expand-md">
    <div class="container-fluid px-0">
      <button
        class="navbar-toggler"
        type="button"
        data-bs-toggle="collapse"
        data-bs-target="#navbarSecondary"
        aria-controls="navbarSecondary"
        aria-expanded="false"
        aria-label="Toggle navigation"
      >
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse flex-row-reverse pt-5 pt-md-0" id="navbarSecondary">
        <form action="{% url 'beneficiaries:index' %}" id="search-beneficiaries" class="mb-0 flex-fill">
          <div class="row">
          </div>
          <div class="row">
            <div class="col-lg-4"></div>
            <div class="col-lg-6">
              {% for field in form %}
                <div class="mb-4 form-required">
                  {% if field.errors %}
                    {{ field|add_class:"form-control is-invalid" }}
                  {% else %}
                    {{ field|add_class:"form-control" }}
                  {% endif %}

                  {% if field.help_text %}
                    <small class="form-text text-muted">{{ field.help_text }}</small>
                  {% endif %}

                  {% if field.errors %}
                    <div class="invalid-feedback fw-bold">
                      {{ field.errors.as_text }}
                    </div>
                  {% endif %}
                  {% if forloop.counter == 1 %}
                    <p class="mt-2 text-center">
                      <span style="background: white;" class="px-3">Ou</span>
                      <span style="margin-top: -12px" class="d-block border-bottom"></span>
                    </p>
                  {% endif %}
                </div>
              {% endfor %}
            {% if form.non_field_errors %}
              <div class="alert alert-danger alert-search-form-empty alert-dismissible" role="alert">
                {{ form.non_field_errors.as_text }}
                <button type="button" class="btn-close" data-bs-hide="alert" aria-label="Fermer"></button>
              </div>
            {% endif %}
            </div>

            <div class="col-lg-2 text-center">
              <div class="row px-2 px-lg-0">
                <button class="btn btn-outline-primary d-block mb-4 mx-md-auto" type="submit">
                  Rechercher &nbsp; {% bs_icon 'search' %}
                </button>
              </div>
              <div class="row">
                <a class="link-secondary fs-6" href="{% url 'beneficiaries:index' %}">Réinitialiser</a>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
  </nav>

  <hr class="mt-1 mb-5" />


  {% if type == "search" %}
    <h4 class="mb-4">Les résultats de votre recherche</h4>
    <div class="row mb-5">
      {% include "beneficiaries/table_search.html" %}
    </div>
    <hr class="mt-1 mb-5" />
  {% endif %}

  <div class="row">
    <div class="col">
      <h4 class="mb-4">{{ title }}</h4>
    </div>

    <div class="col">
      {% if perms.beneficiaries.add_beneficiary and user.is_staff is False %}
        <p class="text-end">
          <a class="btn btn-outline-primary mb-3" role="button" href="{% url 'beneficiaries:new' %}">
            Nouveau &nbsp; {% bs_icon 'plus-circle' %}
          </a>
        </p>
      {% endif %}
    </div>
  </div>

  {% include "beneficiaries/table.html" with beneficiary_list=beneficiary_list %}

  <script>
    const formSearch = document.querySelector("#search-beneficiaries")
    const btnClose = formSearch.querySelector(".btn-close")

    btnClose.addEventListener("click", event => {
      event.preventDefault()
      event.target.parentElement.classList.add("d-none")
    })
  </script>

{% endblock %}

beneficiaries/templates/beneficiaries/show.html
{% extends "master.html" %}

{% block content %}
  <div class="card">
    <div class="card-header py-3">
      Profil {{beneficiary.get_entity_verbose_name}} de : {{ beneficiary }}
    </div>

    <ul class="list-group list-group-flush">
      <li class="list-group-item">Créé le : {{created_at|default_if_none:""}}</li>
      <li class="list-group-item">Structure d’orientation : {{beneficiary.structure_counselor|default_if_none:""}}</li>
      <li class="list-group-item">Structure de médiation : {{beneficiary.structure_operator|default_if_none:""}}</li>
      <li class="list-group-item">Statut : {{beneficiary.get_status}}</li>
      <li class="list-group-item">Prénom : {{beneficiary.first_name}}</li>
      <li class="list-group-item">Nom : {{beneficiary.last_name}}</li>
      <li class="list-group-item">Civilité : {{beneficiary.get_gender}}</li>
      <li class="list-group-item">Classe d’âge : {{beneficiary.age}}</li>
      <li class="list-group-item">Numéro de téléphone : {{beneficiary.phone_number.as_national}}</li>
      <li class="list-group-item">Code d’identification : {{beneficiary.get_huuid}}</li>
      <li class="list-group-item">Niveau du bénéficiaire : {{beneficiary_level|default_if_none:""}}</li>
      <li class="list-group-item">Commentaire de l’orienteur : {{beneficiary.comment|default_if_none:""}}</li>
    </ul>

    <div class="card-footer py-3">
    {% if perms.beneficiaries.change_beneficiary %}
      <a href="{% url 'beneficiaries:edit' beneficiary.id %}" class="btn btn-primary" role="button">Éditer</a>
    {% elif perms.beneficiaries.change_beneficiary_phone %}
      <a href="{% url 'beneficiaries:edit_phone' beneficiary.id %}" class="btn btn-primary" role="button">Éditer le numéro de téléphone</a>
    {% endif %}
    </div>
  </div>

  <div class="text-center"> 
      <a href="{% url 'beneficiaries:index' %}" class="d-block link-primary text-decoration-none mt-2">Retour à la vue d'ensemble</a>
  </div>
  

{% endblock %}

beneficiaries/templates/beneficiaries/table.html
{% if beneficiary_list %}
  <div class="table-responsive">
    <table class="table table-striped table-hover">
      <thead>
        <tr class="align-middle">
          <th>Nom</th>
          <th>Prénom</th>
          <th>Statut</th>
          <th>N° de téléphone</th>
          <th class="text-end pe-4">Actions</th>
        </tr>
      </thead>
      <tbody>
        {% for beneficiary in beneficiary_list %}
          <tr>
            <td>{{ beneficiary.last_name }}</td>
            <td>{{ beneficiary.first_name }}</td>
            <td>{{ beneficiary.get_status }}</td>
            <td>{{ beneficiary.phone_number.as_national }}</td>
            <td class="text-end">
              <a href="{% url 'beneficiaries:show' beneficiary.id %}" class="btn btn-sm btn-primary" title="Voir le bénéficiaire">
                Voir
              </a>

              {% if beneficiary.status != beneficiary.DONE and user.is_staff is False %}

                {% if perms.beneficiaries.assign_beneficiary %}
                  {% if beneficiary.status == beneficiary.CREATED %}
                    <a href="{% url 'beneficiaries:assign_form' beneficiary.id %}" class="btn btn-sm btn-primary" title="Prendre en charge ce bénéficiaire">
                      Prendre en charge
                    </a>
                  {% endif %}
                {% endif %}

                {% if perms.beneficiaries.end_of_support_beneficiary %}
                  {% if beneficiary.status == beneficiary.ACTIVE %}
                    <a href="{% url 'beneficiaries:end_of_support_form' beneficiary.id %}" class="btn btn-sm btn-primary" title="Mettre fin à l'accompagnement">
                      Terminer l’accompagnement
                    </a>
                  {% endif %}
                {% endif %}

              {% endif %}
            </td>
          </tr>
        {% endfor %}
      </tbody>
      <tfoot>
        <tr class="fw-bold">
          <td colspan="5">Total des bénéficiaires : {{ beneficiary_list|length }}</td>
        </tr>
      </tfoot>
    </table>
  </div>
{% else %}
  <div class="alert alert-warning text-center" role="alert">Pas de bénéficiaire </div>
{% endif %}

beneficiaries/templates/beneficiaries/table_search_component.html
{% for beneficiary in beneficiary_list %}
  {% if beneficiary.status != beneficiary.CREATED and beneficiary.structure_operator != user.structure %}
    <tr class="table-active not-allowed" title="Déjà pris en charge par une autre structure">
  {% else %}
    <tr>
  {% endif %}
    <td>{{ beneficiary.last_name }}</td>
    <td>{{ beneficiary.first_name }}</td>
    <td>{{ beneficiary.get_status }}</td>
    <td>{{ beneficiary.get_anonymized_phone_number }}</td>
    <td class="text-end">
      {% if beneficiary.status != beneficiary.DONE and user.is_staff is False %}

        {% if perms.beneficiaries.assign_beneficiary %}
          {% if beneficiary.status == beneficiary.CREATED %}
            <a href="{% url 'beneficiaries:assign_form' beneficiary.id %}" class="btn btn-sm btn-primary" title="Prendre en charge ce bénéficiaire">
              Prendre en charge
            </a>
          {% endif %}
        {% endif %}

        {% if perms.beneficiaries.end_of_support_beneficiary and beneficiary.structure_operator == user.structure %}
          {% if beneficiary.status == beneficiary.ACTIVE %}
            <a href="{% url 'beneficiaries:end_of_support_form' beneficiary.id %}" class="btn btn-sm btn-primary" title="Mettre fin à l'accompagnement">
              Terminer l’accompagnement
            </a>
          {% endif %}
        {% endif %}

      {% endif %}
    </td>
  </tr>
{% endfor %}